### ISSUE TITLE
Problem running on macOS >= 10.12.1 and suggested workaround.

### ISSUE THREAD

**Issue by DrChr** [cyrus-and/gdb-dashboard#104]
I was trying gdb-dashboard on my computer with macOS Sierra 10.12.6 but ran into a problem when attempting to start the program to debug in gdb. Here's the error message:

    >>> start
    Temporary breakpoint 1 at 0x100000fd9: file structured_bindings.cpp, line 19.
    Starting program: XXXXXXXXX
    During startup program terminated with signal ?, Unknown signal.

Note that I've codesigned the gdb executable, so that's not the reason for the error message.

Workaround: Prepend the following line to .gdbinit:

    set startup-with-shell off

The need for this apparently goes back to macOS Sierra 10.12.1: 
    http://blog.adacore.com/gnat-on-macos-sierra

Perhaps this command should be added by default to .gdbinit in the repo. Or perhaps the Python code should attempt to check if on macOS > 10.12.1 and if so have gdb run the command.

Cheers

**Comment by cyrus-and** [comment]
See #81.

I'm assuming that users are able to run GDB in order to try the dashboard, I cannot maintain information about all the tricks that are needed to make GDB work on macOS or other systems. These information should be clearly provided by GDB itself and in fact are part of its wiki: [BuildingOnDarwin](https://sourceware.org/gdb/wiki/BuildingOnDarwin).

But thanks for all the information, this will surely contribute to help others.

**Comment by DrChr** [comment]
I'm afraid you're missing the point.

GDB was working, because of the command I'd added to .gdbinit (that was done  some time ago, so I'd now forgotten about it). Installing gdb-dashboard, replacing .gdbinit, therefore broke my GDB, with the resulting error as described above. Hence my suggestion that the command be included in someway in gdb-dashboard's .gdbinit.
You could also add a warning to your README that exactly following your installation instructions will break GDB on macOS >=10.12.1.

**Comment by cyrus-and** [comment]
GDB dashboard is not meant to replace your own `.gbdinit` file, in fact customization is allowed (and encouraged!) see ["Configuration"][1]. What that means in this case is that (if you want to use GDB with macOS) you'll have a file, say `~/.gdbinit.d/init` containing:

```
set startup-with-shell off
```

[1]: https://github.com/cyrus-and/gdb-dashboard#configuration

**Comment by DrChr** [comment]
I acknowledge that the information can be found by reading the README thoroughly, if you also were to remember/know about the requirement on the command in .gdbinit. However, someone interested in testing gdb-dashboard that just reads the installation section, and not the configuration section seven pages later, may well have broken their GDB as a result. That you don't consider this a potential issue that might at least waste people's time when you could address it with a sentence in the README... oh well.

**Comment by cyrus-and** [comment]
The installation section states "Just place `.gdbinit` in your home directory"; if you **replace** your own `.gdbinit` file you **obviously** lose its content. If you even decide to run `wget -P ~ git.io/.gdbinit` (even without understanding what it does only because some internet dude told you so...) you'll probably end up with nothing changed and a `.gdbinit.1` in your home folder.

All this should remind you that your old init file was there for a reason.
