### ISSUE TITLE
Moving up and down backtrace doesn't refresh the display

### ISSUE THREAD

**Issue by noobaldrin** [cyrus-and/gdb-dashboard#153]
I'm not sure if this is only mine but the display for commands "up" and "down" doesn't refresh.

**Comment by gavinhoward** [comment]
This is an unfortunate side effect of the way `gdb`'s Python API works, so there is not really anything that `gdb-dashboard` can do to fix this.

It has, however, provided a way for *you* to fix it.

By default, `gdb-dashboard` also loads all of the files in `$HOME/.gdbinit.d/`. This means that you can add `gdb` hooks.

Here is how to do that:

1. Create the `$HOME/.gdbinit.d/` directory.
2. Create a file in `$HOME/.gdbinit.d/`; I called mine `hooks`.
3. Paste the following in `$HOME/.gdbinit.d/hooks`:
```
define hookpost-up
    dashboard
end

define hookpost-down
    dashboard
end

define hookpost-frame
    dashboard
end
```
4. Restart `gdb`.

What those hooks do is, at the end of the `up`, `down`, and `frame` commands, it runs the `dashboard` command, which will update the output of `gdb-dashboard`.

Thank you for opening this issue, by the way; now the fix for this is documented for future users. :)

(Also, disclaimer, I am not the maintainer; I am just a passionate user.)

**Comment by noobaldrin** [comment]
It works!

Thanks a lot. :)

**Comment by gavinhoward** [comment]
You're welcome. :)

Just so you know, I cannot close this issue, so if your problem is resolved, please close this issue.

**Comment by noobaldrin** [comment]
Not gonna close without your last say. I'm closing now.

**Comment by cyrus-and** [comment]
Thank you @gavinhoward for the detailed reply!

Also @noobaldrin FYI [hooks][1] are mentioned in the REAME.

[1]: https://github.com/cyrus-and/gdb-dashboard#dashboard--enabled-onoff
