### ISSUE TITLE
Feature request: add comments to assembly

### ISSUE THREAD

**Issue by MrMino** [cyrus-and/gdb-dashboard#187]
Some disassemblers have a functionality that lets users add a comment next to a given line of assembly. It is incredibly helpful when learning asm or reversing a binary with gdb.

It would be nice to have such feature in gdb with dashboard:

```
─── Assembly ───────────────────────────────────────────────────────────────
 0x000000000040145c  ? sub    $0x18,%rsp                                    
 0x0000000000401460  ? mov    %rsi,%rdx                                     
 0x0000000000401463  ? lea    0x4(%rsi),%rcx                                
 0x0000000000401467  ? lea    0x14(%rsi),%rax                               
 0x000000000040146b  ? mov    %rax,0x8(%rsp)                                
 0x0000000000401470  ? lea    0x10(%rsi),%rax                               
 0x0000000000401474  ? mov    %rax,(%rsp)                                   
 0x0000000000401478  ? lea    0xc(%rsi),%r9                                 
 0x000000000040147c  ? lea    0x8(%rsi),%r8                                 
 0x0000000000401480  ? mov    $0x4025c3,%esi                                
 0x0000000000401485  ? mov    $0x0,%eax                                     
```
After command `>>> dashboard assembly comment "A comment here"`, the above assembly would become:
```
─── Assembly ───────────────────────────────────────────────────────────────
 0x000000000040145c  ? sub    $0x18,%rsp            # A comment here             
 0x0000000000401460  ? mov    %rsi,%rdx                                     
 0x0000000000401463  ? lea    0x4(%rsi),%rcx                                
 0x0000000000401467  ? lea    0x14(%rsi),%rax                               
 0x000000000040146b  ? mov    %rax,0x8(%rsp)                                
 0x0000000000401470  ? lea    0x10(%rsi),%rax                               
 0x0000000000401474  ? mov    %rax,(%rsp)                                   
 0x0000000000401478  ? lea    0xc(%rsi),%r9                                 
 0x000000000040147c  ? lea    0x8(%rsi),%r8                                 
 0x0000000000401480  ? mov    $0x4025c3,%esi                                
 0x0000000000401485  ? mov    $0x0,%eax                                     
```

Pretty please :)?

I might even be able to make some PRs for this, if you give a blessing for this feature.

**Comment by cyrus-and** [comment]
Well, this could be useful, but I don't think it would fit in the philosophy of the dashboard which just provides enhancements to basic GDB features, this would be a kind of arbitrary addition better suited to be implemented as a third-party module, possibly extending the original Assembly module.

Admittedly, I didn't developed the dashboard with this particular use case in mind so it's entirely possible that it turns out to be difficult to subclass a module.

Plus, one could extend the same rationale, to a lesser extent, to the Source module, bringing up a whole bunch of additional problems.

It would be easier (yet less effective) to implement a module like:

```
─── Annotations ────────────
A comment here
```

That shows user-defined comments and annotations about the current IP.

I'm OK though to make extending native modules more friendly if needed and if you're willing to explore that avenue.
