### ISSUE TITLE
View GOT/PLT

### ISSUE THREAD

**Issue by katemcguire** [cyrus-and/gdb-dashboard#260]
Hello! I really like gdb-dashboard but recently had to switch to gef as I like the ability to dump the global offset table with the "got" command. pwndbg also has this feature. I believe the information is still accessible using readelf and some math to find the table location, but I'd definitely appreciate this feature being added to gdb dashboard.

**Comment by cyrus-and** [comment]
GEF and Pwndbg focus on exploit development / reversing; gdb-dashboard instead is just an interface for general-purpose GDB usage.

So that would be a pretty niche feature to add, that doesn't really fit in the dashboard philosophy, but nothing prevents you from implementing it in a custom [module][1] or [command][2].

[1]: https://github.com/cyrus-and/gdb-dashboard/wiki/Develop-custom-modules
[2]: https://github.com/cyrus-and/gdb-dashboard/wiki/Develop-custom-commands
