### ISSUE TITLE
Supported architectures

### ISSUE THREAD

**Issue by Tectu** [cyrus-and/gdb-dashboard#263]
Excuse me if I missed this information in the documentation: Is this specific to certain architectures and if so, how would one add support for different architectures?

**Comment by cyrus-and** [comment]
No worries, the dashboard just provides some improved UI with respect to vanilla GDB, but in the end it *is* GDB.

**Comment by Tectu** [comment]
Thank you for your answer. So stuff like the list of registers is not hard-coded for lets say x86 or similar? If I were to use this with lets say a Cortex-M device we'd be good out-of-the-box?

**Comment by cyrus-and** [comment]
> So stuff like the list of registers is not hard-coded for lets say x86 or similar?

Exactly. I strive to add nothing that's platform dependent.

> If I were to use this with lets say a Cortex-M device we'd be good out-of-the-box?

This is sadly a painful point, because GDB apparently fails to give us (programmatically) a way to obtain the list of general purpose registers. So you might experience [issues](https://github.com/cyrus-and/gdb-dashboard/issues?q=is%3Aissue+%22dashboard+registers+-style+list%22+is%3Aclosed) on certain architecture, out-of-the-box. Luckily the fix is trivial, when you come up with such a list you can place the following in a configuration file:

    dashboard registers -style list 'reg1 reg2 reg3 ...'

For a more extended discussion see the above link.

**Comment by Tectu** [comment]
Thank you for your explanation & your efforts!
