### ISSUE TITLE
Provide pretty stack trace as a separate command

### ISSUE THREAD

**Issue by orivej** [cyrus-and/gdb-dashboard#28]
gdb-dashboard stack trace is so readable that it would be great to have it as an individual command. Meanwhile, I switch between
```
define dashboard-stack
  dashboard stack -style limit 0
  dashboard stack -style locals True
  dashboard -layout stack assembly expressions history memory registers source threads
end
```
and
```
define dashboard-default
  dashboard stack -style limit 3
  dashboard stack -style locals False
  dashboard -layout assembly expressions history memory registers source stack threads
end
```

**Comment by cyrus-and** [comment]
I'm glad that you prefer the Stack module over the native implementation and I totally see your point, but I started this project with some principles/ideas in mind; in particular I didn't want to make it another GDB frontend nor a tool which would have imposed some specific workflow to programmers. So I always tried to not add additional commands, in fact everything can be done via the `dashboard` sub/command.

Nevertheless, I wanted it to be as easy *hackable* as possible so in general your approach it does work, but in this case it might be more convenient to play a bit with the internals and use something like this:

```python
define stack
    # create the module
    python stack = Stack()
    # initialize *all* its attributes
    python stack.limit = 0
    python stack.show_arguments = True
    python stack.show_locals = True
    # print the output
    python print('\n'.join(stack.lines(False)))
end
```

This approach has the advantage to avoid unnecessary re-displays of the dashboard and also doesn't clash with your default settings.

You should be able to use something similar to this with any other modules, just take care of reusing the object instead of creating a new one each time if the module is a stateful one (e.g., the list of watched expressions) for example replacing:

```python
python module = Module()
```

with:

```python
python module = locals().get('module', Module())
```

Please let me know if this may fix your issue and if you have any questions please do not hesitate to ask.

**Comment by orivej** [comment]
That is exactly the command I need, thank you!
