### ISSUE TITLE
How do you save the dashboard layout?

### ISSUE THREAD

**Issue by blixelcode** [cyrus-and/gdb-dashboard#307]
1. How do you save the dashboard layout?
2. How do you change the registers to display decimal instead of hex?

Thanks

EDIT: I found that if I make the "~/.gdbinit.d" subdirectory and type "dashboard -configuration ~/.gdbinit.d/init" from within the dashboard, it saves my config. So that takes care of question 1. But I'd still like to know how to change the registers so they display in decimal.

**Comment by vs97849** [comment]
Hi Cyrus,
Had tried some time before. So do not remember now.
Could you please write here step by step instruction so that gdb loads
successfully without error and color coding is maintained in main gdb
session and on tui mode too.
I am using gdb12 , Linux bash shell.

Had downloaded the .gdbinit from your page to my home dir.

Thanks

**Comment by vs97849** [comment]
If you could once try for CentOS on bash,
That would be great. But for me, python errors were there while starting
the gdb

**Comment by cyrus-and** [comment]
> How do you change the registers to display decimal instead of hex?

@blixelcode this is currently not possible, but you can _watch_ the registers you want in whatever radix you want, for example:

    dashboard expressions watch /10 $rax

@vs97849 the dashboard is incompatible with TUI mode, also please don't hijack other issues.
