### ISSUE TITLE
Cannot find Program Counter Index

### ISSUE THREAD

**Issue by Quinny** [cyrus-and/gdb-dashboard#31]
When attempting to walk through the stack of the following code:
https://gist.github.com/Quinny/ae24316e84abacb55729b56a9ff2c875

This error occurs:
![screen shot 2016-04-13 at 12 01 50 pm](https://cloud.githubusercontent.com/assets/4185619/14500335/a5d119da-016f-11e6-8dae-ccb3a59c4384.png)

I am running on OSX 10.10.3.

I added a fix (not sure if it is sufficient though), see my PR https://github.com/cyrus-and/gdb-dashboard/pull/32

**Comment by cyrus-and** [comment]
I see, this happens because the output of the `disassemble` command does not include the program counter:

```
   0x00007fff8fb4a028 <free+400>:	callq  0x7fff8fb5f3fa
   0x00007fff8fb4a02d <free+405>:	mov    %rbx,%rdi
   0x00007fff8fb4a030 <free+408>:	callq  0x7fff8fb5f400
   0x00007fff8fb4a035 <free+413>:	mov    %rax,-0x13b8cad4(%rip)        # 0x7fff7bfbd568
   0x00007fff8fb4a03c <free+420>:	callq  0x7fff8fb5f44e
=> 0x00007fff8fb4a041 <szone_size+0>:	push   %rbp
   0x00007fff8fb4a042 <szone_size+1>:	mov    %rsp,%rbp
   0x00007fff8fb4a045 <szone_size+4>:	push   %rbx
   0x00007fff8fb4a046 <szone_size+5>:	xor    %eax,%eax
   0x00007fff8fb4a048 <szone_size+7>:	test   %rsi,%rsi
   0x00007fff8fb4a04b <szone_size+10>:	je     0x7fff8fb4a333 <szone_size+754>
```

That is, it stops at `<free+420>`, whereas the program counter points to another *function*. I'm using the output of that command because (if I remember correctly) there is no way to reliably obtain the boundaries of the current *function* in all the possible cases, in particular I can't just walk the program counter backwards of n instructions because the grain used by the [`Architecture.disassemble()` function][1] is the byte and not the instruction, so I may end up in starting the disassembly in the middle of an instruction.

Your solution (#32) avoids the exception but shows not meaningful code in the above case. I thinks that it is better to just handle that exception in the same way as the `gdb.error` exception is handled: disassemble twice the context from the program counter itself.

Thanks for reporting this.

[1]: https://sourceware.org/gdb/onlinedocs/gdb/Architectures-In-Python.html
