### ISSUE TITLE
How to move the "Output / messages" pane to the bottom of the layout?

### ISSUE THREAD

**Issue by cirosantilli** [cyrus-and/gdb-dashboard#59]
I know about `-output`, but I just want it to show on the same terminal, but at the bottom.

Rationale: since it is at the top, it makes my source window go up / down all the time after I step when different numbers of line are output.

**Comment by cyrus-and** [comment]
Well, you hit a tricky point here... The "Output/messages" pane is not an actual pane, i.e., it's not explicitly written by the dashboard, rather what I do is trying to *enclose* it between the header and the dashboard itself. That's because there's no easy way to programmatically fetch that messages; AFAIK all that I can do is to prevent GDB from printing them, but that's not an option.

The loop is more or less like this:

1. clean screen and print "Output/messages";
2. the program starts/continues the execution;
3. GDB writes the program output, if any;
4. the program stops;
5. GDB writes information about the break;
6. the dashboard is printed;
7. the prompt is displayed.

I'm afraid what you ask is not easily achievable, but please feel free to share your thoughts about it.

**Comment by cirosantilli** [comment]
Thanks for explaining Cyrus, if your policy is to close harder issues, close away :-)

**Comment by cyrus-and** [comment]
You're welcome!

I'll close it for now because I already faced similar problems and came to the conclusion that *GDB wouldn't let me*, but if I ever find a suitable solution I'll update this thread.

**Comment by czg-sci-42ver** [comment]
as a workaround,maybe you can use 
```bash
gdb-tmux() {
    local id_1="$(tmux display-message -p '#P')"
    local id_3="$(tmux split-pane -vPF "#P")"
    local tty_new_2="$(tmux display-message -p '#{pane_tty}')"
    local id_2="$(tmux split-pane -hPF "#P")"
    local tty_new="$(tmux display-message -p '#{pane_tty}')"

    tmux select-pane -t "$id_1"
    gdb -ex "dashboard source" -ex "dashboard variables" -ex "dashboard source -output $tty_new" -ex "dashboard variables -output $tty_new_2" -ex "start" "$@"
}
gdb-tmux (exe...)
```
to save space to look at message more conveniently, although a little stupid.

inspired by [this wiki](https://github.com/cyrus-and/gdb-dashboard/wiki/Use-multiple-terminals) and [issue](https://github.com/cyrus-and/gdb-dashboard/issues/63#issuecomment-316061215)

**Comment by muhmud** [comment]
Do you think this problem could be solved with gdb's `tty` command?

If so, it's something that could be added to the wiki.

**Comment by cyrus-and** [comment]
@muhmud [this](https://github.com/cyrus-and/gdb-dashboard/wiki/Use-multiple-terminals) is your best bet right now IMHO.

**Comment by muhmud** [comment]
I am using multiple terminals, however, for this, I ended up running `socat` in the tmux pane, instead of `tail` (found this in a useful comment on SO):

```
socat PTY,link=/some/link/path STDIO,cfmakeraw
```

Then, I used a `-ex` to set GDB's `tty` output to the link path:

```
$ gdb -ex "tty /some/link/path" 
```
