### ISSUE TITLE
How can I add other kind of configuration?

### ISSUE THREAD

**Issue by RainVector** [cyrus-and/gdb-dashboard#67]
I want to compactly print matrix of Eigen . So I should configure gdb. There is a python file [here](https://github.com/libigl/eigen/blob/master/debug/gdb/printers.py). 
To use it:
 1.  Create a directory and put the file as well as an empty `__init__.py` in that directory.
 2.  Create a `~/.gdbinit` file, that contains the following:
```
      python
      import sys
      sys.path.insert(0, '/path/to/eigen/printer/directory')
      from printers import register_eigen_printers
      register_eigen_printers (None)
      end
```
But when I append the code above to .gdbinit file of gdb-dashboard,  I can print matrix gracefully, but gdb-dashboard doesn't work anymore. How can I solve this kind problems?

**Comment by cyrus-and** [comment]
Start over with the original `.gdbinit` then place [printers.py][1] (the name is not important) in `~/.gdbinit.d/`.

This is normally enough since files there are automatically evaluated at startup. But in this case you need to run some setup code, so create another file, say `init`, inside your `~/.gdbinit.d/` directory in which you write:

    python register_eigen_printers(None)

FYI that `~/.gdbinit.d/init` file can be used for personal customization instead of modifying the `gdbinit` of the dashboard.

Hope it helps!

[1]: https://github.com/libigl/eigen/blob/master/debug/gdb/printers.py

**Comment by RainVector** [comment]
Great job! Thanks a lot for solving my problems.
