### ISSUE TITLE
Feature request - mixed disassembly in source module

### ISSUE THREAD

**Issue by ajohnson23** [cyrus-and/gdb-dashboard#7]
It'd be nice if the source module allowed for mixed disassembly to be displayed (equivalent of the disassemble [/m flag](https://sourceware.org/gdb/onlinedocs/gdb/Machine-Code.html)).

The mixed dissassembly could be enabled via a style flag on the source module e.g.
```
List of dashboard source -style subcommands:

dashboard source -style disassembly -- Mixed disassembly visibility flag
```
(or it could be a style flag on the Assembly module)

If this were an option, i would probably just turn off the assembly module altogether, then use a quick alias/function to toggle the the mixed disassmbly in the source module.

**Comment by cyrus-and** [comment]
If I implemented such a change then I would better off merging that two modules into one, due to the overlapping of features.

Mixing the two does not significantly reduce the space occupancy. Moreover, I find it confusing to follow the program flow by looking at mixed source/assembly code, IMHO that view is more useful during static code review. But this is just a matter of preference.

Anyway, knowing which assembly code will be executed by the next step is important and in fact it is already marked in the `assembly` module (dim versus bright green in the [screenshot](/cyrus-and/gdb-dashboard#screenshot)).

Thanks for your suggestion.

**Comment by ajohnson23** [comment]
I agree that this is more of a personal preference thing. I also think that the Python disassemble gdb function doesn't support the /m mode so it may not be super easy to implement. Thanks for the consideration.
