### ISSUE TITLE
Negative offsets in disassembly are displayed as `some_symbol+-23`

### ISSUE THREAD

**Issue by 10110111** [cyrus-and/gdb-dashboard#72]
Test program generator:
```
gcc -m32 -x c -o test -g -O3 - <<< 'inline int inlined(int x) { return x*1234; } int main() {volatile int x=1244; return inlined(x);}'
```
To reproduce, take the output file of the above command and try doing `start`, and then single-stepping `main` in assembly. When you go to `imul` instruction, which is marked as belonging to the `inlined()` function, the _Assembly_ module looks like this:
```
─── Assembly ───────────────────────────────────────
0x08048366 inlined+-11 mov    DWORD PTR [ebp-0x4],0x4dc
0x0804836d inlined+-4 mov    eax,DWORD PTR [ebp-0x4]
0x08048370 inlined+-1 leave  
0x08048371 inlined+0 imul   eax,eax,0x4d2
0x08048377 inlined+6 ret    
─────────────────────────────────────────────────
```
I'd expect `inlined+-11` to look like `inlined-11` instead, and similarly for other negative offsets.

**Comment by cyrus-and** [comment]
The root of this problem is that AFAIK it's not possible to obtain the function bounds with GDB, I could fix the sign or simply omit the function name and offset for negative value but in either case there would be a misleading `inlined+6` after, which is not wrong in principle but it may suggest that `ret` is part of `inlined`.

All in all, I think the best option is to simply fix the sign.
