### ISSUE TITLE
Unable to work gdb-dashboard

### ISSUE THREAD

**Issue by ismailhkose** [cyrus-and/gdb-dashboard#82]
I am getting the following errors in my Ubuntu 16.04 and GDB 8.0. Any idea?
Do i need to configure for any special configuration while building GDB to support gdb-dashboard?

```
(gdb) source test/.gdbinit
^[[H^[[J^[[31mCannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 358, in render
  File "<string>", line 864, in lines
IndexError: list index out of range^[[0m
^[[H^[[J^[[31mCannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 358, in render
  File "<string>", line 864, in lines
IndexError: list index out of range^[[0m
^A^[[1;35m^B>>>^A^[[0m^B
```

I installed pygmentize and UIFlows but it didnt help at all.

Also, tried to run dashboard command in my PC and getting the following error. Is dashboard a special tool that needs to be installed.

> zsh: command not found: dashboard

Thanks

**Comment by cyrus-and** [comment]
> Do i need to configure for any special configuration while building GDB to support gdb-dashboard?

GDB need to be compiled with Python (>= 2.7), but this is not your problem.

> Also, tried to run dashboard command in my PC and getting the following error. Is dashboard a special tool that needs to be installed.

Nope, the dashboard only lives within GDB.

> Any idea?

This error seems to be about the Assembly module, in particular about the parsing of the `disassemble` GDB command. Can you show me what happens if you issue the `disassemble` command instead of `source test/.gdbinit`? Thanks.

**Comment by cyrus-and** [comment]
Bump.
