### ISSUE TITLE
Issues when changing frame

### ISSUE THREAD

**Issue by lucianposton** [cyrus-and/gdb-dashboard#88]
![out](https://user-images.githubusercontent.com/646121/31185149-1d294dea-a8e0-11e7-9f56-0991ab1c3361.gif)

- After changing the frame, `frame 3`, when I display the dashboard, `dashboard`, the program resumes similar to as if I had typed `continue`.
- Following from the above scenario, the stack now shows that a function was called from gdb (highlighted in the gif).

**Comment by lucianposton** [comment]
fyi, I wasn't able to repro this bug on another project that had source code.

**Comment by cyrus-and** [comment]
There is nothing in the dashboard itself that could explain such behavior. But it's possible that some *complex* functions are called from GDB, thus triggering a breakpoint or (as in this case) reading from stdin.

Try to do the same with plain GDB and see if it happens.

**Comment by lucianposton** [comment]
Can't repro the issue using plain gdb, `gdb -n`.

Anymore info I can provide to help?

fyi, here is the binary I'm using to repo this issue ( the x86_64 tarball download at http://www.unrealworld.fi/urw_linuxmirror.html ). I ctrl-c the program to interrupt it when it is at the main menu. Then I `frame 3` to change the frame.

**Comment by cyrus-and** [comment]
OK I got this, and it's quite weird actually... I use `gdb.parse_and_eval(frame.name()).address` to obtain the function start address. Now, usually `frame.name()` yields the name of the function (e.g., `nanosleep`), but in this case it returns `getkey()` which is fed into `gdb.parse_and_eval` and thus is called.

The problem is that AFAIK there is no other ways to obtain the function start address, I could simply trim the frame name to the first `(`...

**Comment by cyrus-and** [comment]
It should work now, please give it a try. Thanks for reporting this issue.

**Comment by lucianposton** [comment]
@cyrus-and That worked. Thanks

If you think that's a bug in gdb's python api, it might be worth reporting in gdb's bug database. https://www.gnu.org/software/gdb/bugs/
