### ISSUE TITLE
Saving "Current Configuration State" back to your gdbinit

### ISSUE THREAD

**Issue by MikeBrWade** [cyrus-and/gdb-dashboard#92]
Once you have a layout/style/setup it would be nice to save all that off to either the gdbinit or one of the user configuration files.  The more you  use the tool the more little scripts and modifications you make and keeping your configuration updated can be challenging manually.

**Comment by cyrus-and** [comment]
I agree that it would be a nice feature to have, but I would limit that to styles (dashboard itself and modules) and layout.

I'm not sure about `dashboard [<modulel>] -output` since the TTY name is not meaningful across sessions, yet it might be if filenames are provided...

I don't think that adding hooks, GDB-related stuff (e.g., breakpoints) or the result of module commands (e.g., `dashboard memory watch`) would be a good idea though.

**Comment by MikeBrWade** [comment]
Oh I agree, not the gdb state.  Just the layout, configuration of styles, and honestly I think the dashboard <mod> -output would be super usefull at least for tmux where you can pretty easily predict the order of your /dev/pts/XX count by the order the tmux is created and windows are created inside it.

**Comment by cyrus-and** [comment]
[Implemented][1], give it a spin. Thanks for the suggestion!

[1]: https://github.com/cyrus-and/gdb-dashboard#dashboard--configuration-file

**Comment by MikeBrWade** [comment]
Wow nice, in the middle of a debug session didn't expect you do that so quick.  I will try it soon though.  Can I just pull down the latest and do "source" on it instead of rebooting gdb?

**Comment by cyrus-and** [comment]
Never really tried this, but yeah it should be possible.
