### ISSUE TITLE
Doesn't work well in non-stop mode

### ISSUE THREAD

**Issue by amosbird** [cyrus-and/gdb-dashboard#99]
Hi, when doing `dashboard` command in non-stop mode, gdb selects other running threads instead of the current suspended one. Is there a way to resolve this? Thanks!

**Comment by cyrus-and** [comment]
Please provide an easy way for me to reproduce what you're experiencing since in my experiments this seems not to happen.

The only problem is that the "Thread" module cannot fetch frame information for background running thread thus causing an exception, I'm going to fix this... (This might explain your issue but you should have noticed the error.)

**Comment by amosbird** [comment]
Yes, that error keeps pumping out. But I never thought it's related... I'll try to construct  a minimal test case.

**Comment by amosbird** [comment]
It is fixed! Thanks!
